# Generated by Django 5.2.3 on 2025-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_message_created_at_remove_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='aixplain_session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
